### ISSUE TITLE
Stundenplan-Algorithmus

### ISSUE THREAD

**Issue by Spycner** [Spycner/GrundPlaner#4]
**Titel:** Algorithmus zur Erstellung von Stundenplänen entwickeln

**Beschreibung:**

Entwickeln Sie einen Algorithmus, der unter Berücksichtigung der in den Notizen beschriebenen Restriktionen und Anforderungen automatisch Stundenpläne für die Schule erstellt. Der Algorithmus sollte in der Lage sein, einen optimalen Stundenplan zu generieren, der den Bedürfnissen von Schülern, Lehrern und dem Schulpersonal gerecht wird.

**Akzeptanzkriterien:**

- Der Algorithmus sollte alle in den Notizen beschriebenen Restriktionen und Anforderungen berücksichtigen.
- Der Algorithmus sollte in der Lage sein, einen optimalen Stundenplan zu generieren.
- Der entwickelte Algorithmus sollte gut dokumentiert und leicht verständlich sein.

**Comment by polini** [comment]
OptaPlanner gefällt mir ganz gut, da gibt es auch schon ein Schul-Beispiel:
- https://www.optaplanner.org/learn/useCases/schoolTimetabling.html
- https://github.com/kiegroup/optaplanner-quickstarts/tree/stable/hello-world
